server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:                                    # 多个服务
        - id: payment_routh                      # 路由的ID，没有固定的规则但是要求唯一，建议配合服务名
          uri: http://localhost:8001             # 匹配后提供服务的地址
          predicates:                            #
            - Path=/payment/getPaymentById/**    # 断言，路径相匹配的进行路由

        - id: payment_routh2                     # 路由的ID，没有固定的规则但是要求唯一，建议配合服务名
          uri: http://localhost:8001             # 匹配后提供服务的地址
          predicates:                            #
            - Path=/payment/lb/**                # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka